### ISSUE TITLE
Register page password area not support all special characters.

### ISSUE THREAD

**Issue by ozers** [napse-invest/Napse#17]
I tried to register with password for example "123456-Abc"  ['Password must contain at least 1 special character.'] ( - [minus] character not accepted)

**Comment by tomjeannesson** [comment]
We are looking into it right now. @Xenepix will answer as soon as he's located the issue.

**Comment by Xenepix** [comment]
Hello, thanks a lot for the feedback! Minus is now considered a special character :)

**Comment by tomjeannesson** [comment]
@ozers the code is in production, please let us know if you still have issues
